delete from restaurants;
delete from visitors;

insert into restaurants (id, name, description, street, zip, city) values (null, 'DAR ES-SOLTANE', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.', '23, rue Hamlaoui', '25000', 'Constantine');
insert into restaurants (id, name, description, street, zip, city) values (null, 'TIDDIS', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.', 'Avenue Ali-Zaamouche', '25000', 'Constantine');
insert into restaurants (id, name, description, street, zip, city) values (null, 'CAFE NEDJMA', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.', '1, avenue Rahmani-Achour', '25000', 'Constantine');
insert into restaurants (id, name, description, street, zip, city) values (null, 'HOTEL CIRTA', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.', 'Undefined', '25000', 'Constantine');
insert into restaurants (id, name, description, street, zip, city) values (null, 'QSAR', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.', 'Cité des Arcades Romaines', '25000', 'Constantine');
insert into restaurants (id, name, description, street, zip, city) values (null, 'JANNAH RESTAURANT', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.', 'Undefined', '25000', 'Constantine');
insert into restaurants (id, name, description, street, zip, city) values (null, 'DAR DIAF', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.', 'Undefined', '25000', 'Constantine');
insert into restaurants (id, name, description, street, zip, city) values (null, 'BUON GUSTO', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.', 'Sid Mabrouk inférieur', '25000', 'Constantine');
insert into restaurants (id, name, description, street, zip, city) values (null, 'MAGIC FOOD', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.', 'Undefined', '25000', 'Constantine');
insert into restaurants (id, name, description, street, zip, city) values (null, 'LA QUEEN FOOD', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.', 'Undefined', '25000', 'Constantine');
insert into restaurants (id, name, description, street, zip, city) values (null, 'IGHERSEEN', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.', 'Undefined', '25000', 'Constantine');
insert into restaurants (id, name, description, street, zip, city) values (null, 'PATISSERIE CASSONADE', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.', '58, rue Arbi Ben Mehdi', '25000', 'Constantine');
insert into restaurants (id, name, description, street, zip, city) values (null, 'PATISSERIE DELICE CONSTANTINE', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.', 'Undefined', '25000', 'Constantine');
insert into restaurants (id, name, description, street, zip, city) values (null, 'PIZZERIA LA STRESA', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.', 'Undefined', '25000', 'Constantine');
insert into restaurants (id, name, description, street, zip, city) values (null, 'CAFE BEYROUTH', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.', 'Undefined', '25000', 'Constantine');
insert into restaurants (id, name, description, street, zip, city) values (null, 'CAFETERIA SNACK OXUGENE', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.', 'Undefined', '25000', 'Constantine');
insert into restaurants (id, name, description, street, zip, city) values (null, 'CHICKEN LAND', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.', 'N3', '25000', 'Constantine');
insert into restaurants (id, name, description, street, zip, city) values (null, 'AL BAIK', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.', '25, rue Hamlaoui', '25000', 'Constantine');
insert into restaurants (id, name, description, street, zip, city) values (null, 'METRO FOOD', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.', 'Cité Kouthil Lakhdar', '25000', 'Constantine');

insert into visitors (id, fullname, username, password) values (null, 'Mahamet Habibou', 'Mahamet2018', 'password');
insert into visitors (id, fullname, username, password) values (null, 'Souley Ladan', 'Souley2018', 'password');
insert into visitors (id, fullname, username, password) values (null, 'Boubacar Moussa', 'Moussa2018', 'password');
insert into visitors (id, fullname, username, password) values (null, 'Karimou Seyni', 'Karimou2018', 'password');
insert into visitors (id, fullname, username, password) values (null, 'Arzika Sabiou', 'Arzika2018', 'password');
insert into visitors (id, fullname, username, password) values (null, 'Mainassara Moussa', 'Mainassara2018', 'password');
insert into visitors (id, fullname, username, password) values (null, 'Boubacar Bako', 'Bako2018', 'password');
insert into visitors (id, fullname, username, password) values (null, 'Aboubacar Sani', 'Sani2018', 'password');
insert into visitors (id, fullname, username, password) values (null, 'Chegou Bosso', 'Chegou2018', 'password');
insert into visitors (id, fullname, username, password) values (null, 'Badam Mamane', 'Badam2018', 'password');

insert into grades (restaurant_id, visitor_id, food_quality, room_quality, service_quality, quality, graduate_at) values (1, 5, 12, 13, 15, 14, '2018-10-17 01:50:55.618');
insert into grades (restaurant_id, visitor_id, food_quality, room_quality, service_quality, quality, graduate_at) values (1, 10, 15, 16, 14, 15, '2018-10-17 01:50:55.618');
insert into grades (restaurant_id, visitor_id, food_quality, room_quality, service_quality, quality, graduate_at) values (1, 1, 7, 14, 14, 12, '2018-10-17 01:50:55.618');
insert into grades (restaurant_id, visitor_id, food_quality, room_quality, service_quality, quality, graduate_at) values (1, 2, 16, 13, 16, 15, '2018-10-17 01:50:55.618');
insert into grades (restaurant_id, visitor_id, food_quality, room_quality, service_quality, quality, graduate_at) values (2, 3, 5, 16, 17, 13, '2018-10-17 01:50:55.618');
insert into grades (restaurant_id, visitor_id, food_quality, room_quality, service_quality, quality, graduate_at) values (2, 4, 13, 17, 9, 13, '2018-10-17 01:50:55.618');
insert into grades (restaurant_id, visitor_id, food_quality, room_quality, service_quality, quality, graduate_at) values (2, 5, 18, 16, 13, 13, '2018-10-17 01:50:55.618');
insert into grades (restaurant_id, visitor_id, food_quality, room_quality, service_quality, quality, graduate_at) values (3, 6, 15, 14, 11, 14, '2018-10-17 01:50:55.618');
insert into grades (restaurant_id, visitor_id, food_quality, room_quality, service_quality, quality, graduate_at) values (3, 7, 12, 17, 12, 10, '2018-10-17 01:50:55.618');
insert into grades (restaurant_id, visitor_id, food_quality, room_quality, service_quality, quality, graduate_at) values (4, 8, 17, 18, 16, 14, '2018-10-17 01:50:55.618');
insert into grades (restaurant_id, visitor_id, food_quality, room_quality, service_quality, quality, graduate_at) values (4, 9, 18, 17, 18, 18, '2018-10-17 01:50:55.618');
insert into grades (restaurant_id, visitor_id, food_quality, room_quality, service_quality, quality, graduate_at) values (4, 10, 14, 13, 14, 14, '2018-10-17 01:50:55.618');
insert into grades (restaurant_id, visitor_id, food_quality, room_quality, service_quality, quality, graduate_at) values (4, 1, 16, 16, 16, 16, '2018-10-17 01:50:55.618');
insert into grades (restaurant_id, visitor_id, food_quality, room_quality, service_quality, quality, graduate_at) values (4, 2, 12, 15, 17, 10, '2018-10-17 01:50:55.618');
insert into grades (restaurant_id, visitor_id, food_quality, room_quality, service_quality, quality, graduate_at) values (8, 3, 14, 14, 16, 15, '2018-10-17 01:50:55.618');
insert into grades (restaurant_id, visitor_id, food_quality, room_quality, service_quality, quality, graduate_at) values (8, 4, 13, 13, 17, 15, '2018-10-17 01:50:55.618');
insert into grades (restaurant_id, visitor_id, food_quality, room_quality, service_quality, quality, graduate_at) values (17, 5, 11, 16, 16, 15, '2018-10-17 01:50:55.618');
insert into grades (restaurant_id, visitor_id, food_quality, room_quality, service_quality, quality, graduate_at) values (17, 6, 18, 18, 14, 17, '2018-10-17 01:50:55.618');
insert into grades (restaurant_id, visitor_id, food_quality, room_quality, service_quality, quality, graduate_at) values (17, 7, 12, 17, 14, 15, '2018-10-17 01:50:55.618');
insert into grades (restaurant_id, visitor_id, food_quality, room_quality, service_quality, quality, graduate_at) values (9, 8, 15, 14, 12, 14, '2018-10-17 01:50:55.618');
insert into grades (restaurant_id, visitor_id, food_quality, room_quality, service_quality, quality, graduate_at) values (9, 9, 19, 12, 13, 15, '2018-10-17 01:50:55.618');
